Repository pagopa/pagopa-negative-biz-events-datastore, pull requests merged in 2023-05, with the labels that each got.

#3 feat: Sviluppo ingestion eventi negativi [PAGOPA-783]
  .devops/deploy-pipelines-standard.yml
  .devops/deploy-pipelines.yml
  .env.example
  .gitignore
  Dockerfile
  helm/values-dev.yaml
  integration-test/run_integration_test.sh
  integration-test/src/README.md
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/negative-biz-events-processor.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/support/biz_event_step.js
  integration-test/src/step_definitions/support/common.js
  integration-test/src/step_definitions/support/datastore_client.js
  integration-test/src/step_definitions/support/event_hub_client.js
  local.settings.json.example
  pom.xml
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/NegativeBizEventToDatastore.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/NegativeBizEventsToEventHub.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/BizEvent.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/Creditor.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/Debtor.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/DebtorPosition.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/MBD.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/MapEntry.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/PaymentInfo.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/Psp.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/Transfer.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/exception/AppException.java
  src/test/java/it/gov/pagopa/negativebizeventsdatastore/NegativeBizEventsToDatastoreTest.java
  src/test/java/it/gov/pagopa/negativebizeventsdatastore/NegativeBizEventsToEventHubTest.java
  src/test/java/it/gov/pagopa/negativebizeventsdatastore/util/TestUtil.java
  src/test/resources/events/negativeBizEvents.json
Labels: enhancement

#4 test: Set-up integration test GHA based [PAGOPA-786]
  .github/workflows/anchore.yml
  .github/workflows/assignee.yml
  .github/workflows/check_metadata_pr.yml
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/deploy.yml
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  .github/workflows/self_hosted.yml
  .github/workflows/sonar_analysis.yml
  .github/workflows/update_code.yml
  .github/workflows/update_infra.yml
  docker/README.md
  docker/docker-compose.yml
  docker/run_docker.sh
  integration-test/README.MD
  integration-test/run_integration_test.sh
Labels: enhancement, size/large

#5 test: Set-up integration test [PAGOPA-786]
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/integration_test.yml
  .github/workflows/self_hosted.yml
  .github/workflows/update_code.yml
  .github/workflows/update_infra.yml
  .gitignore
  .identity/.terraform.lock.hcl
  .identity/00_locals.tf
  .identity/00_main.tf
  .identity/00_variables.tf
  .identity/01_data.tf
  .identity/02_application_action.tf
  .identity/02_application_action_auth.tf
  .identity/03_github_environment.tf
  .identity/99_outputs.tf
  .identity/env/dev/backend.ini
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.ini
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  .identity/terraform.sh
  docker/docker-compose.yml
  docker/run_docker.sh
  integration-test/src/features/negative-biz-events-processor.feature
  integration-test/src/package.json
Labels: enhancement, size/large

#6 ci: Update and release in UAT environment
  .devops/deploy-pipelines.yml
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/config/.env.uat
  integration-test/src/step_definitions/support/biz_event_step.js
Labels: ignore-for-release, size/small

#7 PAGOPA-911-biz-evt-test-gestione-eventi-negativi-per-pdnd
  .github/workflows/code_review.yml
  .github/workflows/integration_test.yml
  .identity/01_data.tf
  .identity/03_github_environment.tf
  integration-test/src/README.md
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/features/negative-biz-events-processor.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/support/biz_event_step.js
  integration-test/src/step_definitions/support/common.js
  integration-test/src/step_definitions/support/datastore_client.js
  integration-test/src/step_definitions/support/kafka_listener.js
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/Info.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/NegativeBizEventToDatastore.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/NegativeBizEventsToEventHub.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/BizEvent.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/Creditor.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/Debtor.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/DebtorPosition.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/MapEntry.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/PaymentInfo.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/Psp.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/entity/Transfer.java
  src/main/java/it/gov/pagopa/negativebizeventsdatastore/exception/AppException.java
  src/test/java/it/gov/pagopa/negativebizeventsdatastore/InfoTest.java
  src/test/java/it/gov/pagopa/negativebizeventsdatastore/NegativeBizEventsToDatastoreTest.java
  src/test/java/it/gov/pagopa/negativebizeventsdatastore/NegativeBizEventsToEventHubTest.java
  src/test/java/it/gov/pagopa/negativebizeventsdatastore/util/TestUtil.java
Labels: enhancement, size/large

#8 ci(kubectl): add KubectlInstaller in uat deploy pipeline
  .devops/deploy-pipelines.yml
Labels: bug, size/small
